on: [push]
name: Azure ARM
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./infra/main.bicep
        parameters: 'apiManagementServiceName=aoia-apim-test-demo publisherEmail=yyakoubi@microsoft.com aoaiPrimaryAccount=${{ secrets.AOIAPRIMARYACCOUNT }} aoaiSecondaryAccount=${{ secrets.AOIASECONDARYACCOUNT }} aoaiPrimaryLLMDeployment=${{ secrets.AOAIPRIMARYLLMDEPLOYMENT }} aoaiSecondaryLLMDeployment=${{ secrets.AOAIPRIMARYLLMDEPLOYMENT }} '
        failOnStdErr: false
